export const insightsList = [
  {
    id: "1",
    link: "insights/articles/cloud-ai",
    image: "/images/cloud/2.jpg",
    uptitle: "DATA & ANALYTICS",
    title:
      "Cloud and AI take center stage: global study reveals unwavering priority amid challenges",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "2",
    image: "/images/cloud/4.jpg",
    link: "insights/cases/our-law-firms-success-story",
    uptitle: "LEAD GENERATION",
    title: "A 240% Lead Surge: Our Law Firm's Success Story",
    refer: "Case Studies",
    timing: "4 min",
  },
  {
    id: "3",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "4",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "5",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "6",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "7",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "8",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "9",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "10",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "11",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "12",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "13",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "14",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "15",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "16",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "1",
    link: "insights/articles/cloud-ai",
    image: "/images/cloud/4.jpg",
    uptitle: "DATA & ANALYTICS",
    title:
      "Cloud and AI take center stage: global study reveals unwavering priority amid challenges",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "2",
    image: "/images/cloud/4.jpg",
    link: "insights/cases/our-law-firms-success-story",
    uptitle: "LEAD GENERATION",
    title: "A 240% Lead Surge: Our Law Firm's Success Story",
    refer: "Case Studies",
    timing: "4 min",
  },
  {
    id: "3",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "4",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "5",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "6",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "7",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "8",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "9",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "10",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "11",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "12",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "13",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "14",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "15",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "16",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "1",
    link: "insights/articles/cloud-ai",
    image: "/images/cloud/1.jpg",
    uptitle: "DATA & ANALYTICS",
    title:
      "Cloud and AI take center stage: global study reveals unwavering priority amid challenges",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "2",
    image: "/images/cloud/4.jpg",
    link: "insights/cases/our-law-firms-success-story",
    uptitle: "LEAD GENERATION",
    title: "A 240% Lead Surge: Our Law Firm's Success Story",
    refer: "Case Studies",
    timing: "4 min",
  },
  {
    id: "3",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "4",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "5",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "6",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "7",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "8",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "9",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "10",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "11",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "12",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "13",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "14",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "15",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "16",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "1",
    link: "insights/articles/cloud-ai",
    image: "/images/cloud/3.jpg",
    uptitle: "DATA & ANALYTICS",
    title:
      "Cloud and AI take center stage: global study reveals unwavering priority amid challenges",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "2",
    image: "/images/cloud/4.jpg",
    link: "insights/cases/our-law-firms-success-story",
    uptitle: "LEAD GENERATION",
    title: "A 240% Lead Surge: Our Law Firm's Success Story",
    refer: "Case Studies",
    timing: "4 min",
  },
  {
    id: "3",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "4",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "5",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "6",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "7",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "8",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "9",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "10",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "11",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "12",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "13",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "14",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "15",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
  {
    id: "16",
    image: "/images/insights/1.jpg",
    link: "#",
    uptitle: "DATA & ANALYTICS",
    title:
      "Achieve your business objectives with agility using actionable insights.",
    refer: "Articles",
    timing: "4 min",
  },
];
